description: >
  Docker executor for running Cypress with a sidecar MySQL container.
docker:
  # Primary container image where all steps run.
  - image: gravitywiz/cypress-with-wp:apache
  - image: 'circleci/mysql:<<parameters.mysql>>'
    environment:
      MYSQL_HOST: 127.0.0.1
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_HOST: "%"
parameters:
  mysql:
    default: 5.7
    description: >
      Pick a specific circleci/node image variant:
      https://hub.docker.com/r/cimg/node/tags
    type: string
